---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Criar um usuário no Github
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Criar um projeto
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Instalar o Github
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Indicar quem tem permissões no repositório
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Fazer `git push origin master`
  checked: true
name: Com licença
