---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: En mi computadora
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: En la nube
  checked: true
name: Nube arriba, nube abajo
