---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Crear un usuario en Github
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Crear un proyecto
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Instalar Github
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Indicar quién tiene permisos en el repositorio
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Hacer `git push origin master`
  checked: true
name: Con permiso
